# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@next/env-12.1.0" = {
      name = "_at_next_slash_env";
      packageName = "@next/env";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/env/-/env-12.1.0.tgz";
        sha512 = "nrIgY6t17FQ9xxwH3jj0a6EOiQ/WDHUos35Hghtr+SWN/ntHIQ7UpuvSi0vaLzZVHQWaDupKI+liO5vANcDeTQ==";
      };
    };
    "@next/swc-android-arm64-12.1.0" = {
      name = "_at_next_slash_swc-android-arm64";
      packageName = "@next/swc-android-arm64";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-android-arm64/-/swc-android-arm64-12.1.0.tgz";
        sha512 = "/280MLdZe0W03stA69iL+v6I+J1ascrQ6FrXBlXGCsGzrfMaGr7fskMa0T5AhQIVQD4nA/46QQWxG//DYuFBcA==";
      };
    };
    "@next/swc-darwin-arm64-12.1.0" = {
      name = "_at_next_slash_swc-darwin-arm64";
      packageName = "@next/swc-darwin-arm64";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-darwin-arm64/-/swc-darwin-arm64-12.1.0.tgz";
        sha512 = "R8vcXE2/iONJ1Unf5Ptqjk6LRW3bggH+8drNkkzH4FLEQkHtELhvcmJwkXcuipyQCsIakldAXhRbZmm3YN1vXg==";
      };
    };
    "@next/swc-darwin-x64-12.1.0" = {
      name = "_at_next_slash_swc-darwin-x64";
      packageName = "@next/swc-darwin-x64";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-darwin-x64/-/swc-darwin-x64-12.1.0.tgz";
        sha512 = "ieAz0/J0PhmbZBB8+EA/JGdhRHBogF8BWaeqR7hwveb6SYEIJaDNQy0I+ZN8gF8hLj63bEDxJAs/cEhdnTq+ug==";
      };
    };
    "@next/swc-linux-arm-gnueabihf-12.1.0" = {
      name = "_at_next_slash_swc-linux-arm-gnueabihf";
      packageName = "@next/swc-linux-arm-gnueabihf";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm-gnueabihf/-/swc-linux-arm-gnueabihf-12.1.0.tgz";
        sha512 = "njUd9hpl6o6A5d08dC0cKAgXKCzm5fFtgGe6i0eko8IAdtAPbtHxtpre3VeSxdZvuGFh+hb0REySQP9T1ttkog==";
      };
    };
    "@next/swc-linux-arm64-gnu-12.1.0" = {
      name = "_at_next_slash_swc-linux-arm64-gnu";
      packageName = "@next/swc-linux-arm64-gnu";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm64-gnu/-/swc-linux-arm64-gnu-12.1.0.tgz";
        sha512 = "OqangJLkRxVxMhDtcb7Qn1xjzFA3s50EIxY7mljbSCLybU+sByPaWAHY4px97ieOlr2y4S0xdPKkQ3BCAwyo6Q==";
      };
    };
    "@next/swc-linux-arm64-musl-12.1.0" = {
      name = "_at_next_slash_swc-linux-arm64-musl";
      packageName = "@next/swc-linux-arm64-musl";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-arm64-musl/-/swc-linux-arm64-musl-12.1.0.tgz";
        sha512 = "hB8cLSt4GdmOpcwRe2UzI5UWn6HHO/vLkr5OTuNvCJ5xGDwpPXelVkYW/0+C3g5axbDW2Tym4S+MQCkkH9QfWA==";
      };
    };
    "@next/swc-linux-x64-gnu-12.1.0" = {
      name = "_at_next_slash_swc-linux-x64-gnu";
      packageName = "@next/swc-linux-x64-gnu";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-x64-gnu/-/swc-linux-x64-gnu-12.1.0.tgz";
        sha512 = "OKO4R/digvrVuweSw/uBM4nSdyzsBV5EwkUeeG4KVpkIZEe64ZwRpnFB65bC6hGwxIBnTv5NMSnJ+0K/WmG78A==";
      };
    };
    "@next/swc-linux-x64-musl-12.1.0" = {
      name = "_at_next_slash_swc-linux-x64-musl";
      packageName = "@next/swc-linux-x64-musl";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-linux-x64-musl/-/swc-linux-x64-musl-12.1.0.tgz";
        sha512 = "JohhgAHZvOD3rQY7tlp7NlmvtvYHBYgY0x5ZCecUT6eCCcl9lv6iV3nfu82ErkxNk1H893fqH0FUpznZ/H3pSw==";
      };
    };
    "@next/swc-win32-arm64-msvc-12.1.0" = {
      name = "_at_next_slash_swc-win32-arm64-msvc";
      packageName = "@next/swc-win32-arm64-msvc";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-arm64-msvc/-/swc-win32-arm64-msvc-12.1.0.tgz";
        sha512 = "T/3gIE6QEfKIJ4dmJk75v9hhNiYZhQYAoYm4iVo1TgcsuaKLFa+zMPh4056AHiG6n9tn2UQ1CFE8EoybEsqsSw==";
      };
    };
    "@next/swc-win32-ia32-msvc-12.1.0" = {
      name = "_at_next_slash_swc-win32-ia32-msvc";
      packageName = "@next/swc-win32-ia32-msvc";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-ia32-msvc/-/swc-win32-ia32-msvc-12.1.0.tgz";
        sha512 = "iwnKgHJdqhIW19H9PRPM9j55V6RdcOo6rX+5imx832BCWzkDbyomWnlzBfr6ByUYfhohb8QuH4hSGEikpPqI0Q==";
      };
    };
    "@next/swc-win32-x64-msvc-12.1.0" = {
      name = "_at_next_slash_swc-win32-x64-msvc";
      packageName = "@next/swc-win32-x64-msvc";
      version = "12.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@next/swc-win32-x64-msvc/-/swc-win32-x64-msvc-12.1.0.tgz";
        sha512 = "aBvcbMwuanDH4EMrL2TthNJy+4nP59Bimn8egqv6GHMVj0a44cU6Au4PjOhLNqEh9l+IpRGBqMTzec94UdC5xg==";
      };
    };
    "caniuse-lite-1.0.30001317" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001317";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001317.tgz";
        sha512 = "xIZLh8gBm4dqNX0gkzrBeyI86J2eCjWzYAs40q88smG844YIrN4tVQl/RhquHvKEKImWWFIVh1Lxe5n1G/N+GQ==";
      };
    };
    "nanoid-3.3.1" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.1.tgz";
        sha512 = "n6Vs/3KGyxPQd6uO0eH4Bv0ojGSUvuLlIHtC3Y0kEO23YRge8H9x1GCzLn28YX0H66pMkxuaeESFq4tKISKwdw==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "postcss-8.4.5" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.4.5.tgz";
        sha512 = "jBDboWM8qpaqwkMwItqTQTiFikhs/67OYVvblFFTM7MrZjt6yMKd6r2kgXizEbTTljacm4NldIlZnhbjr84QYg==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "styled-jsx-5.0.0" = {
      name = "styled-jsx";
      packageName = "styled-jsx";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/styled-jsx/-/styled-jsx-5.0.0.tgz";
        sha512 = "qUqsWoBquEdERe10EW8vLp3jT25s/ssG1/qX5gZ4wu15OZpmSMFI2v+fWlRhLfykA5rFtlJ1ME8A8pm/peV4WA==";
      };
    };
    "use-subscription-1.5.1" = {
      name = "use-subscription";
      packageName = "use-subscription";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use-subscription/-/use-subscription-1.5.1.tgz";
        sha512 = "Xv2a1P/yReAjAbhylMfFplFKj9GssgTwN7RlcTxBujFQcloStWNDQdc4g4NRWH9xS4i/FDk04vQBptAXoF3VcA==";
      };
    };
  };
in
{
  next = nodeEnv.buildNodePackage {
    name = "next";
    packageName = "next";
    version = "12.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/next/-/next-12.1.0.tgz";
      sha512 = "s885kWvnIlxsUFHq9UGyIyLiuD0G3BUC/xrH0CEnH5lHEWkwQcHOORgbDF0hbrW9vr/7am4ETfX4A7M6DjrE7Q==";
    };
    dependencies = [
      sources."@next/env-12.1.0"
      sources."@next/swc-android-arm64-12.1.0"
      sources."@next/swc-darwin-arm64-12.1.0"
      sources."@next/swc-darwin-x64-12.1.0"
      sources."@next/swc-linux-arm-gnueabihf-12.1.0"
      sources."@next/swc-linux-arm64-gnu-12.1.0"
      sources."@next/swc-linux-arm64-musl-12.1.0"
      sources."@next/swc-linux-x64-gnu-12.1.0"
      sources."@next/swc-linux-x64-musl-12.1.0"
      sources."@next/swc-win32-arm64-msvc-12.1.0"
      sources."@next/swc-win32-ia32-msvc-12.1.0"
      sources."@next/swc-win32-x64-msvc-12.1.0"
      sources."caniuse-lite-1.0.30001317"
      sources."nanoid-3.3.1"
      sources."object-assign-4.1.1"
      sources."picocolors-1.0.0"
      sources."postcss-8.4.5"
      sources."source-map-js-1.0.2"
      sources."styled-jsx-5.0.0"
      sources."use-subscription-1.5.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The React Framework";
      homepage = "https://nextjs.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
